import React from 'react';
import Header from '../components/header';
import Footer from '../components/footer';

const Page = () => {
  return (
    <main>
      <Header />
      <div className="relative overflow-hidden bg-white">
        <div className="relative isolate px-6 pt-14 lg:px-8">
          <div className="mx-auto max-w-3xl pt-32 pb-24 sm:pt-48 pb-44 lg:pt-56 pb-48">
            <div className="text-center">
              <h1 className="text-balance text-4xl font-bold tracking-tight text-gray-900 sm:text-7xl">
                Unlock the Power of Your Mind
              </h1>
              <p className="mt-8 text-pretty lg:text-lg font-medium text-gray-500 leading-loose">
                Our Brain-Computer Interface (BCI) is a groundbreaking tool that bridges the gap between human thoughts and machine actions.
              </p>
            </div>
          </div>

          <div className="mx-auto max-w-4xl py-10 sm:py-20 lg:py-24">
            <h2 className="text-4xl mb-6 font-bold text-gray-900 ">How It Works</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-10">
              <div className="group bg-gray-100 p-6 rounded-md  text-left transition-all duration-500 hover:bg-primary">
                <h2 className="text-xl font-semibold text-gray-900 mb-3 capitalize transition-all duration-500 group-hover:text-white">Data Collection</h2>
                <p className="text-sm font-normal text-gray-500 transition-all duration-500 leading-5 group-hover:text-white">
                  It all starts with high-quality, gold-coated electrodes placed on your scalp. These electrodes detect the electrical signals (EEG) generated by your brain. Conductive paste ensures optimal contact for accurate signal capture.
                </p>
              </div>

              <div className="group bg-gray-100 p-6 rounded-md  text-left transition-all duration-500 hover:bg-primary ">
                <h2 className="text-xl font-semibold text-gray-900 mb-3 capitalize transition-all duration-500 group-hover:text-white">Signal Amplification</h2>
                <p className="text-sm font-normal text-gray-500 transition-all duration-500 leading-5 group-hover:text-white">
                  The signals collected from your brain are incredibly weak. To make them usable, we use AD620 instrumentation amplifiers to amplify these signals while preserving their integrity.
                </p>
              </div>

              <div className="group bg-gray-100 p-6 rounded-md  text-left transition-all duration-500 hover:bg-primary">
                <h2 className="text-xl font-semibold text-gray-900 mb-3 capitalize transition-all duration-500 group-hover:text-white">Wireless Transmission</h2>
                <p className="text-sm font-normal text-gray-500 transition-all duration-500 leading-5 group-hover:text-white">
                  Once amplified, the signals are transmitted wirelessly to your computer using the ESP32 microcontroller, eliminating the need for bulky wires and ensuring seamless data flow.
                </p>
              </div>

              <div className="group bg-gray-100 p-6 rounded-md  text-left transition-all duration-500 hover:bg-primary">
                <h2 className="text-xl font-semibold text-gray-900 mb-3 capitalize transition-all duration-500 group-hover:text-white"> Real-Time Data Processing</h2>
                <p className="text-sm font-normal text-gray-500 transition-all duration-500 leading-5 group-hover:text-white">
                  The transmitted signals are analyzed on our secure server using cutting-edge machine learning algorithms. These algorithms decode the brain’s activity patterns and convert them into actionable commands.
                </p>
              </div>

              <div className="group bg-gray-100 p-6 rounded-md  text-left transition-all duration-500 hover:bg-primary">
                <h2 className="text-xl font-semibold text-gray-900 mb-3 capitalize transition-all duration-500 group-hover:text-white">Action Execution</h2>
                <p className="text-sm font-normal text-gray-500 transition-all duration-500 leading-5 group-hover:text-white">
                  Finally, the processed data is sent to our web app, where it translates into actions, like typing on a keyboard. The intuitive interface makes controlling your computer with your mind simple and effective.
                </p>
              </div>


            </div>
            <div className="mx-auto max-w-4xl py-16 sm:py-20 lg:py-24">
              <div className="text-left">
                <h2 className="text-4xl mb-8 font-bold text-gray-900">Key Technologies</h2>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">🧠</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">Gold-Coated Electrodes</h3>
                  <p className="text-sm text-gray-600">High-quality, non-invasive sensors ensure accurate brain signal detection.</p>
                </div>

                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">⚡</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">AD620 Amplifiers</h3>
                  <p className="text-sm text-gray-600">Instrumentation amplifiers precisely amplify weak brain signals.</p>
                </div>

                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">📡</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">ESP32 Microcontroller</h3>
                  <p className="text-sm text-gray-600">Handles wireless data transfer with efficiency and reliability.</p>
                </div>

                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">🔐</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">FastAPI Backend</h3>
                  <p className="text-sm text-gray-600">Ensures secure and fast data handling with modern web technologies.</p>
                </div>

                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">🌐</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">Next.js Frontend</h3>
                  <p className="text-sm text-gray-600">Offers a smooth and responsive user interface for real-time control.</p>
                </div>

                <div className="bg-gray-100 p-6 rounded-lg shadow-md text-center transition-all duration-300 hover:shadow-lg">
                  <div className="flex justify-center items-center mb-4">
                    <span className="text-primary text-5xl">🤖</span>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">Machine Learning</h3>
                  <p className="text-sm text-gray-600">Processes brain signals to interpret activity patterns into commands.</p>
                </div>
              </div>
            </div>


          </div>
        </div>
      </div>
      <Footer />
    </main>
  );
};

export default Page;
